name: Test

on:
    push:

jobs:
    tests:
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        steps:
            - uses: szenius/set-timezone@v1.0
              with:
                  timezoneLinux: 'US/Central'
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: bahmutov/npm-install@v1
            - name: Preflight
              run: yarn run pf
            - name: Run tests
              run: yarn run ci
